spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    testWhileIdle: false
  redis:
    host: localhost
    port: 6379
    redisson:
      config: classpath:redis-dev.yml
mybatis-plus:
  mapper-locations: classpath:/mapperxml/**.xml
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
redisson:
  address: redis://127.0.0.1:6379